In [13]:
import autograd as ad

from autograd import grad, jacobian
import autograd.numpy as np

In [14]:
def myfunc(x):
    return x[0]**2*x[1]**3

z = np.array([5,3],dtype=float)

jacobian_func = jacobian(myfunc)
jacobian_func(z)

array([270., 675.])

### Linear System of Equations
$$
x-2y+3z=7 \\
2x + y + z = 4 \\
-3x + 2y -2z = -10
$$

### Solution:
$$
\left(x,y,z\right) = \left(2,-1,1\right)
$$

In [15]:
func1 = lambda x:    x[0] - 2*x[1] + 3*x[2] - 7
func2 = lambda x:  2*x[0] -   x[1] +   x[2] - 4
func3 = lambda x: -3*x[0] - 2*x[1] - 2*x[2] + 10


In [16]:
jac_func1 = jacobian(func1)
jac_func2 = jacobian(func2)
jac_func3 = jacobian(func3)


### Multivariate Case: Newton Rhapson Updating Rule
  $$
  \left[ {\begin{array}{cc}
    x_1 \\
    . \\
    . \\
    .\\
    x_N
  \end{array} } \right] = 
    \left[ {\begin{array}{cc}
    x_1 \\
    . \\
    . \\
    .\\
    x_M
  \end{array} } \right]_{N \cdot 1} - 
    \left[ {\begin{array}{cc}
    J^{-1}(x_n)
  \end{array} } \right]_{N \cdot M}
    \left[ {\begin{array}{cc}
    f_1(x_n) \\
    . \\
    . \\
    .\\
    f_M(x_N)
  \end{array} } \right]_{M \cdot 1}
  $$

In [17]:
i = 0
error   = 100
tol     = 1e-8
maxiter = 1000
M = 3
N = 3

x_0 = np.array([1,1,1],dtype=float).reshape(N,1)

while np.any(abs(error) > tol) and i < maxiter:

    fun_evaluate = np.array([func1(x_0),func2(x_0),func3(x_0)]).reshape(M,1)

    flat_x_0 = x_0.flatten()

    jac = np.array([jac_func1(flat_x_0),jac_func2(flat_x_0),jac_func3(flat_x_0)])
    jac = jac.reshape(N,M)

    x_new = x_0 - np.linalg.inv(jac) @ fun_evaluate

    error = x_new - x_0

    x_0 = x_new
    print(i)
    print(error)
    print("----------")

    i = i + 1

print("The solution is\n",
        x_new,
        "\nEq-1", np.around(func1(x_new),3),
        "\nEq-2", np.around(func2(x_new),3),
        "\nEq-3", np.around(func3(x_new),3))



0
[[ 0.15789474]
 [-0.21052632]
 [ 1.47368421]]
----------
1
[[-4.44089210e-16]
 [ 3.33066907e-16]
 [ 4.44089210e-16]]
----------
The solution is
 [[1.15789474]
 [0.78947368]
 [2.47368421]] 
Eq-1 [0.] 
Eq-2 [0.] 
Eq-3 [0.]
