In [12]:
import autograd as ad

from autograd import grad, jacobian
import autograd.numpy as np

In [13]:
def myfunc(x):
    return x[0]**2*x[1]**3

z = np.array([5,3],dtype=float)

jacobian_func = jacobian(myfunc)
jacobian_func(z)

array([270., 675.])

### Linear System of Equations
$$
x-2y+3z=7 \\
2x + y + z = 4 \\
-3x + 2y -2z = -10
$$

### Solution:
$$
\left(x,y,z\right) = \left(2,-1,1\right)
$$

In [14]:
func1 = lambda x:    x[0] - 2*x[1] + 3*x[2] - 7
func2 = lambda x:  2*x[0] +   x[1] +   x[2] - 4
func3 = lambda x: -3*x[0] + 2*x[1] - 2*x[2] + 10


In [15]:
jac_func1 = jacobian(func1)
jac_func2 = jacobian(func2)
jac_func3 = jacobian(func3)


### Multivariate Case: Newton Rhapson Updating Rule
  $$
  \left[ {\begin{array}{cc}
    x_1 \\
    . \\
    . \\
    .\\
    x_N
  \end{array} } \right] = 
    \left[ {\begin{array}{cc}
    x_1 \\
    . \\
    . \\
    .\\
    x_M
  \end{array} } \right]_{N \cdot 1} - 
    \left[ {\begin{array}{cc}
    J^{-1}(x_n)
  \end{array} } \right]_{N \cdot M}
    \left[ {\begin{array}{cc}
    f_1(x_n) \\
    . \\
    . \\
    .\\
    f_M(x_N)
  \end{array} } \right]_{M \cdot 1}
  $$

In [16]:
i = 0
error   = 100
tol     = 1e-8
maxiter = 1000
M = 3
N = 3

x_0 = np.array([1,1,1],dtype=float).reshape(N,1)

while np.any(abs(error) > tol) and i < maxiter:

    fun_evaluate = np.array([func1(x_0),func2(x_0),func3(x_0)]).reshape(M,1)

    flat_x_0 = x_0.flatten()

    jac = np.array([jac_func1(flat_x_0),jac_func2(flat_x_0),jac_func3(flat_x_0)])
    jac = jac.reshape(N,M)

    x_new = x_0 - np.linalg.inv(jac) @ fun_evaluate

    error = x_new - x_0

    x_0 = x_new
    print(i)
    print(error)
    print("----------")

    i = i + 1

print("The solution is\n",
        x_new,
        "\nEq-1", np.around(func1(x_new),3),
        "\nEq-2", np.around(func2(x_new),3),
        "\nEq-3", np.around(func3(x_new),3))



0
[[ 1.00000000e+00]
 [-2.00000000e+00]
 [-1.11022302e-16]]
----------
1
[[0.]
 [0.]
 [0.]]
----------
The solution is
 [[ 2.]
 [-1.]
 [ 1.]] 
Eq-1 [0.] 
Eq-2 [0.] 
Eq-3 [0.]


### Linear System of Equations
$$
3x_1 - \cos{x_2 x_3} + \frac{3}{2} = 0 \\
4x_{1}^{2} - 625x_{2}^{2} + 2x_{3} - 1 = 0 \\
20 x_3 + e^{-x_{1}x_{2}} + 9 = 0
$$

### Solution:
$$
\left(x_1,x_2,x_3\right) = \left(0.83328161,0.03533462,-0.49854928\right)
$$

In [17]:
func111 = lambda x: 3*x[0] - np.cos(x[1]*x[2])-(3/2)
func222 = lambda x: 4*(x[0]**2) - 625*(x[1]**2) + 2*x[2] - 1
func333 = lambda x: 20*x[2] + np.exp(-x[0]*x[1]) + 9

In [21]:
def NewtRhap_3(vector_func):

    func11 = vector_func[0]
    func22 = vector_func[1]
    func33 = vector_func[2]

    jac_func11 = jacobian(func11)
    jac_func22 = jacobian(func22)
    jac_func33 = jacobian(func33)

    i = 0
    error = 100
    tol = 1e-10
    maxiter = 1000
    M = 3
    N = 3

    x_0 = np.array([1, 1, 1], dtype=float).reshape(N, 1)

    while np.any(abs(error) > tol) and i < maxiter:

        fun_evaluate = np.array(
            [func11(x_0), func22(x_0), func33(x_0)]).reshape(M, 1)

        flat_x_0 = x_0.flatten()

        jac = np.array([jac_func11(flat_x_0), jac_func22(
            flat_x_0), jac_func33(flat_x_0)])
        jac = jac.reshape(N, M)

        x_new = x_0 - np.linalg.inv(jac) @ fun_evaluate

        error = x_new - x_0

        x_0 = x_new
    #    print(i)
    #    print(error)
    #    print("----------")

        i = i + 1

    print('Iterations:', i,
          '\nError:\n', error,
          '\n-------------------')
    print("The solution is\n",
          x_new,
          "\nEq-1", np.around(func11(x_new), 3),
          "\nEq-2", np.around(func22(x_new), 3),
          "\nEq-3", np.around(func33(x_new), 3))


In [22]:
vec = [func111,func222,func333]
NewtRhap_3(vec)

Iterations: 10 
Error:
 [[ 0.00000000e+00]
 [-6.93889390e-18]
 [-1.11022302e-16]] 
-------------------
The solution is
 [[ 0.83328161]
 [ 0.03533462]
 [-0.49854928]] 
Eq-1 [0.] 
Eq-2 [-0.] 
Eq-3 [0.]


In [23]:
vec1 = [func1, func2, func3]
NewtRhap_3(vec1) 

Iterations: 2 
Error:
 [[0.]
 [0.]
 [0.]] 
-------------------
The solution is
 [[ 2.]
 [-1.]
 [ 1.]] 
Eq-1 [0.] 
Eq-2 [0.] 
Eq-3 [0.]
